include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
  exclude:
    - "ios/**"
    - "pubspec*"
    - "android/**"
    - "lib/**/*.g.dart"
    - "lib/firebase_options.dart"
