name: symbols_icon_pack
description: "Flutter package that provides Symbol Icons. A file icon pack for code editors."
homepage: https://softyes.com.br
repository: https://github.com/softyesti/symbols_icon_pack

version: 0.1.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  very_good_analysis: ^6.0.0
  icon_generator: ^4.0.3

flutter:
  fonts:
    - family: SymbolsFolderIcons
      fonts:
        - asset: assets/fonts/symbols_folder_icons.ttf
